// Login events
export const SESSION_SIGNUP = 'SESSION_SIGNUP';
export const SESSION_LOGIN = 'SESSION_LOGIN';
export const SESSION_LOADING = 'SESSION_LOADING';
export const SESSION_SUCCESS = 'SESSION_SUCCESS';
export const SESSION_ERROR = 'SESSION_ERROR';
